name: Simple CI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    

    steps:
      - name: ğŸ“œ Chockout code
        uses: actions/checkout@v5.0.0


      - name: show runtime context
        run: |
          echo "ğŸ“ Workflow: ${{ github.workflow }}"
          echo "ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸŒ¿ Branch: ${{ github.ref }}"
          echo "ğŸš€ Trigged by: ${{ github.event_name }}"
          echo "ğŸ¤µ Actor: ${{ github.actor }}"
          echo " ğŸ”§Runner OS: ${{ matrix.os }}"
          echo "ğŸ”¢ Run number: ${{ github.run_number }}"

      

      - name: ğŸ› ï¸ Setup .NET 9
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 9.0.x

      - name: ğŸ”„ï¸ Restore dependencies
        working-directory: Bankapp/Bankapp
        run: dotnet restore

      - name: ğŸ§± Build project
        working-directory: Bankapp/Bankapp
        run: dotnet build --no-restore --configuration Release
      
